import Head from 'next/head'
import Image from 'next/image'
import drake from "../assets/ALDrake.png"
import Header from '../components/Header';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Google Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>
      {/* <Body/> */}

      <footer className="flex items-center justify-center h-screen">
        <a
          href="https://al-drake.netlify.app/"
          target="_blank"
          rel="noopener noreferrer">
          Made with ❤️ by{" AL Drake "}
          <span>
            <Image
              src={drake}
              alt="Drake photo"
              width={32}
              height={32}
            />
          </span>
        </a>
      </footer>
    </div>
  );
}
